CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_NEWLIB_LIBC=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_GPIO=y
CONFIG_PRINTK=y

#
# RTFrame master switches - CM4 minimal config (all OFF)
#
CONFIG_RTFRAME_CORE=n
CONFIG_RTFRAME_LIB=n
CONFIG_RTFRAME_DRIVERS=n
CONFIG_RTFRAME_MODULES=n
CONFIG_RTFRAME_MIDDLEWARE=n
